#!/usr/bin/env python2.7

import sys, copy
sys.path.insert(0, 'Resource')
sys.path.insert(0, 'Prism')
sys.path.insert(0, '../data')

from constant import *
import prism_compute as Computer
import prism_encode_adv as Encoder
import prism_extension_adv as Prism
import data_handler as Data
from util import *


def processExtension(result, lastFrequent,
 lastSeqBlocks, lastOffsets, lastPosBlocks, 
 seqBlocksList, posOffsetsList, posBlocksList, 
 items, isSeqExt):
	lengthOfItems = len(items)

	for itemIndex in xrange(0, lengthOfItems):
		curItem 							= items[itemIndex]
		seqBlockTarget 				= seqBlocksList[itemIndex]
		posOffsetsListTarget 	= posOffsetsList[itemIndex]
		posBlocksTarget 			= posBlocksList[itemIndex]

		# Avoid duplicate labeling if extend itemset
		if isSeqExt == False and string(lastFrequent).findAdv(curItem) != -1:
			continue

		(seqBlocksExt, posOffsetsExt, posBlocksExt) = Prism.extend(
			lastFrequent, curItem,
			lastSeqBlocks, seqBlockTarget,
			lastOffsets, posOffsetsListTarget,
			lastPosBlocks, posBlocksTarget,
			isSeqExt
		)

		supp = Computer.computeSupportOfPrimalValueArray(seqBlocksExt)

		# print " => Last frequence: {0} support {1}".format(lastFrequent, supp)

		if supp >= MIN_SUPP:
			if isSeqExt == True:
				lastFrequent += "->{0}".format(curItem)
			else:
				lastFrequent += ".{0}".format(curItem)

			# Ensure to make a copy instead of assign reference
			_lastSeqBlocks 	= copy.deepcopy(seqBlocksExt)
			_lastPosOffsets = copy.deepcopy(posOffsetsExt)
			_lastPosBlocks 	= copy.deepcopy(posBlocksExt)

			processExtension(result, lastFrequent, _lastSeqBlocks, _lastPosOffsets, _lastPosBlocks, seqBlocksList, posOffsetsList, posBlocksList, items, True)
			processExtension(result, lastFrequent, _lastSeqBlocks, _lastPosOffsets, _lastPosBlocks, seqBlocksList, posOffsetsList, posBlocksList, items, False)

			result.append({
				"frequent": lastFrequent,
				"support": supp
			})

			numerOfCharsRemove = len(curItem)
			if isSeqExt == True:
				numerOfCharsRemove += 2
			else:
				numerOfCharsRemove += 1

			lastFrequent = lastFrequent[:-numerOfCharsRemove]

	return


if __name__ == "__main__":
	(itemsPosBlocks, itemsPosOffsets) = Encoder.processEncodePrimalBlockAllSequences(ITEMS, SEQUENCES)
	seqBlocks = Encoder.processEncodePrimalSeqAdv(ITEMS, SEQUENCES)

	numberOfItems = len(ITEMS)
	result = [[]] * numberOfItems

	for index in xrange(0, numberOfItems):
		processExtension(result[index], ITEMS[index], 
			seqBlocks[index], itemsPosOffsets[index], itemsPosBlocks[index], 
			seqBlocks, itemsPosOffsets, itemsPosBlocks,
			ITEMS, True
		)

		processExtension(result[index], ITEMS[index], 
			seqBlocks[index], itemsPosOffsets[index], itemsPosBlocks[index], 
			seqBlocks, itemsPosOffsets, itemsPosBlocks,
			ITEMS, False
		)

	# for element in result[index]:
	# 	print "{0} - {1}".format(element["frequent"], element["support"])
	
	testCase = "H.G->Q"
	# Find a sequence pattern
	for element in result[index]:	 
		isExist = True if element["frequent"].find(testCase) != -1 else False
		if isExist:
			print "{0} - {1}".format(element["frequent"], element["support"])






